[build]
  functions = "main/functions"

[dev]
  functions = "main/functions"

# Redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
