[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

# Redirects and rewrites
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
